version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: loginuser
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: social
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: